<a href="https://colab.research.google.com/github/gundaminpde/2023-spring/blob/main/01_1_python_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a modifiction of the CS231n Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

# **Basic data types**


Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.



# Numbers
Integers and floats work as you would expect from other languages:

In [1]:
x = 3
print (x, type(x))

3 <class 'int'>


In [6]:
print (x + 1)   # Addition;
print (x - 1)   # Subtraction;
print (x * 2)   # Multiplication;
print (x ** 2)  # Exponentiation;

4
2
6
9


In [10]:
## 복합연산자

x += 1
print (x)  # Prints "4"
x *= 2
print (x)  # Prints "8"

4
8


In [11]:
y = 2.5
print (type(y))
print (y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


In [6]:
print(round(123/45,1))
print(round(123/45,2))
print(round(123/45,3))

2.7
2.73
2.733


In [7]:
100+int('100')

200

# Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [14]:
t, f = True, False
print (type(t)) # Prints ""
print (type(f))

<class 'bool'>
<class 'bool'>


In [16]:
print (t and f) # Logical AND;
print (t or f)  # Logical OR;
print (not t)   # Logical NOT;
print (t != f)  # Logical XOR;
     

False
True
False
True


In [8]:
print(bool(1))
print(bool(0))

True
False


In [9]:
100<200

True

# Strings

In [17]:

hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print (hello, len(hello))

hello 5


In [18]:
hw = hello + ' ' + world  # String concatenation
print (hw)  # prints "hello world"

hello world


In [19]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print (hw12)  # prints "hello world 12"

hello world 12


In [3]:
## 상황에 맞게 처리해 준다.
a=1
b=2
c=1.5
d="Hello World"

print(a+b)
print(b+c)
print(d)

print(type(b))
print(type(c))
print(type(d))

3
3.5
Hello World
<class 'int'>
<class 'float'>
<class 'str'>


String objects have a bunch of useful methods; for example:

In [20]:

s = "hello"
print (s.capitalize())  # Capitalize a string; prints "Hello"
print (s.upper())       # Convert a string to uppercase; prints "HELLO"
print (s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print (s.center(7) )    # Center a string, padding with spaces; prints " hello "
print (s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print ('  world '.strip())  # Remove leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the documentation.
https://docs.python.org/3.5/library/stdtypes.html#string-methods

In [4]:

your_name = input('이름이 뭔데?')
print("너의 이름은",your_name)


이름이 뭔데?주성치
너의 이름은 주성치


# **if and while : conditional sentences**

In [11]:
## if 문

answer = input("주성치 영화를 본 적이 있나요? (예/아니요):")

if answer == "예":
    print("진정한 영화를 보았군요.")
elif answer == "아니요":
    print("아쉽군요.")
else:
    print("예/아니오로 대답하시라.")

주성치 영화를 본 적이 있나요? (예/아니요):뭐라구요?
예/아니오로 대답하시라.


In [10]:
hungry = True

if hungry:
    print("배고파요")
     

배고파요


In [13]:
aaa = 1

while aaa <= 5:
  aaa+=1
  print(aaa)

#print(aaa)

print("끝")

2
3
4
5
6
끝


# **Containers**
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

# Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [14]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
len(xs)

[3, 1, 2] 2
2


3

In [25]:
xs[2] = 'foo'    # Lists can contain elements of different types
print (xs)

[3, 1, 'foo']


In [26]:
xs.append('bar') # Add a new element to the end of the list
print(xs) 

[3, 1, 'foo', 'bar']


In [27]:
x = xs.pop()     # Remove and return the last element of the list
print (x, xs)

bar [3, 1, 'foo']


In [15]:
## 문자열의 경우

s = 'DaDsasdfAAAghj'

print(s[0])
print(s[3])
print(s[-3])


D
s
g


In [16]:
aaa=[12,6,3,4,5,34,6,6,5]

print(aaa[1:5])

aaa.append(20)
print(aaa)

aaa+=[30]
print(aaa)

bbb=aaa
print(bbb)

del bbb[2:8]
print(bbb)
print(aaa) ## 같은 실체

aaa=aaa+[2,3]
print(aaa)

[6, 3, 4, 5]
[12, 6, 3, 4, 5, 34, 6, 6, 5, 20]
[12, 6, 3, 4, 5, 34, 6, 6, 5, 20, 30]
[12, 6, 3, 4, 5, 34, 6, 6, 5, 20, 30]
[12, 6, 5, 20, 30]
[12, 6, 5, 20, 30]
[12, 6, 5, 20, 30, 2, 3]


In [17]:

ccc= [[1,2,3],[2,2,3],[1,1]]
print(ccc)

threeby3= [[1,2,3],[2,2,3],[1,1,2]]
print(threeby3)

ccc[1][0]

empty=[]

empty2=list()

print(empty)
print(empty2)

[[1, 2, 3], [2, 2, 3], [1, 1]]
[[1, 2, 3], [2, 2, 3], [1, 1, 2]]
[]
[]


In [19]:
## 행렬

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

X = np.array([[1],[4],[7]])

print(A)
print(X)
print(len(A))
print("행렬크기 = ", np.shape(X))  ## 매우 중요

print('행렬곱 AX = ', A@X, sep ='\n')

print('matmul 사용',np.matmul(A, X), sep ='\n')

print('dot 사용',np.dot(A, X), sep ='\n')
print(A+X)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
3
행렬크기 =  (3, 1)
행렬곱 AX = 
[[ 30]
 [ 66]
 [102]]
matmul 사용
[[ 30]
 [ 66]
 [102]]
dot 사용
[[ 30]
 [ 66]
 [102]]
[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]]


# Slicing


In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:



In [22]:

nums = list(range(0,10,2)) # range is a built-in function that can creates a list of integers

print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4]=[8,9] # Assign a new sublist to a slice
print(nums )        # Prints "[0, 1, 8, 9, 4]"

[0, 2, 4, 6, 8]
[4, 6]
[4, 6, 8]
[0, 2]
[0, 2, 4, 6, 8]
[0, 2, 4, 6]
[0, 2, 8, 9, 8]


# **Loops**

You can loop over the elements of a list like this:

In [35]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [36]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


# List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [38]:

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)
     

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [40]:

nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


In [42]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)
     

[0, 4, 16]


# Dictionaries

A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [57]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print (d['cat'])      # Get an entry from a dictionary; prints "cute"
print ('cat' in d)    # Check if a dictionary has a given key; prints "True"

cute
True


In [58]:

d['fish'] = 'wet'    # Set an entry in a dictionary
print (d['fish'])      # Prints "wet"
     

wet


In [59]:
print (d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: ignored

In [60]:

print (d.get('monkey', '없다')) # Get an element with a default; prints "없다", monkey의 값을 찾고, monkey가 없다면 '없다'라고 말하라.
print (d.get('fish', '없다'))   # Get an element with a default; prints "wet"

없다
wet


In [61]:
del d['fish']        # Remove an element from a dictionary
print (d)
print (d.get('fish', '없다')) # "fish" is no longer a key; prints "N/A"

{'cat': 'cute', 'dog': 'furry'}
없다


In [62]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the iteritems method:

In [72]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d.items(): 
    print ('A %s has  %d legs ' % animal)

A person has  2 legs 
A cat has  4 legs 
A spider has  8 legs 


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [74]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print (even_num_to_square)

{0: 0, 2: 4, 4: 16}


# Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [76]:

animals = {'cat', 'dog'}
print ('cat' in animals)   # Check if an element is in a set; prints "True"
print ('fish' in animals)  # prints "False"

True
False


In [77]:
animals.add('fish')      # Add an element to a set
print ('fish' in animals)
print (len(animals) )      # Number of elements in a set;

True
3


In [78]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print (len(animals) )      
animals.remove('cat')    # Remove an element from a set
print (len(animals) )

3
2


In [79]:

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: dog
#3: cat


In [81]:
from math import sqrt

print ({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


# Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [82]:

d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print (type(t))
print (d[t])       
print (d[(1, 2)])

<class 'tuple'>
5
1


In [83]:

t[0] = 1

TypeError: ignored

In [23]:
aaa=tuple()
aaa=1,2,3,4
print(aaa)
aaa=5,6,7,8
print(aaa)
bbb=()
print(bbb)
aaa[2]=100

(1, 2, 3, 4)
(5, 6, 7, 8)
()


TypeError: ignored

In [24]:
### unpacking

aaa = '바', '다', '에', '왕', '자'
q,w,r,t,y=aaa
print(w)

## 리스트도 가능

bbb=[1,2,3,4]
x,y,z,w = bbb 
print(x)

## x,y,z,w,l = bbb 

다
1


In [25]:

# tuple => dictionary

exmpl = [('a', '벰'), ('b', '베라'), ('c', '베로')]

print(exmpl)

dic_exmpl = dict(exmpl)

print(dic_exmpl)

print(type(dic_exmpl))

print(dic_exmpl['b'])

[('a', '벰'), ('b', '베라'), ('c', '베로')]
{'a': '벰', 'b': '베라', 'c': '베로'}
<class 'dict'>
베라


In [27]:
## enumerate() : 일회용

AAA = ['AAA는', '자동차', '협회']

BBB = enumerate(AAA)

print(BBB)

for i in BBB:
   print(i)

for j, k in BBB:
    print("이건 작동안해요",j, k)

(0, 'AAA는')
(1, '자동차')
(2, '협회')


In [28]:
## enumerate()

AAA = ['AAA는', '자동차', '협회']

BBB = enumerate(AAA)

print(BBB)

for j, k in BBB:
    print("이건 작동해요",j, k)

for i in BBB:
   print(i)


이건 작동해요 0 AAA는
이건 작동해요 1 자동차
이건 작동해요 2 협회


# **Functions**

Python functions are defined using the def keyword. For example:

In [29]:

def baboya():
  print("바보야")

baboya()

바보야


In [33]:
# 기본적인 함수 반사

def BanSa(word):
  return word

BanSa('펭수')

'펭수'

In [32]:

# 학생들이 좋아하는 range() 함수와 인수


A1= list (range(10)) # 인수 한 개

A2= list (range(2,10)) # 인수 한 개

A3= list (range(2,10,3)) # 인수 한 개


print('A1=',A1)

print('A2=',A2)

print('A3=',A3)

A1= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A2= [2, 3, 4, 5, 6, 7, 8, 9]
A3= [2, 5, 8]


In [84]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print (sign(x))

negative
zero
positive


In [34]:
# 기본적인 함수 반사을 위한 기본(default) 값

def BanSa2(word='침묵'):
  return word

print(BanSa2('펭수'))
print(BanSa2())

펭수
침묵


In [86]:
def hello(name, loud=False):
    if loud:
        print ('HELLO, %s' % name.upper())
    else:
        print ('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


In [30]:
## 전역변수

def in_out():
##  global word
  word="A"
  print(word)

word="B"

in_out()

print(word)
     

A
B


In [31]:
## 전역변수 2

def in_out():
  global word
  word="A"
  print(word)

word="B"

in_out()

print(word)
     

A
A


In [35]:

# 위치인수 positional arguments와 가변인수 variable length arguments

def print_movies(*movies):
  for title in movies:
    print(title)

print_movies('당산대형','정무문','맹룡과강','용쟁호투','사망유희')

당산대형
정무문
맹룡과강
용쟁호투
사망유희


In [36]:
### 새로운 함수다.

def separation(*words, sep='*'):
  return sep.join(words)

separation('ahrada','dsgf','ujyhgtds')

'ahrada*dsgf*ujyhgtds'

In [37]:
separation('ahrada','dsgf','ujyhgtds',sep='%%%%%%%')

'ahrada%%%%%%%dsgf%%%%%%%ujyhgtds'

In [38]:
separation(sep='%%%%%%%','ahrada','dsgf','ujyhgtds') ### 순서가 바뀌니 안된다.

SyntaxError: ignored

In [39]:
### 언패킹을 통해 튜플 대입하기

numbers = 3, 15

list(range(*numbers)) ## '*'를 사용하여 unpacking하여 넣었다.

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

# **Classes**

The syntax for defining classes in Python is straightforward:

In [87]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print ('HELLO, %s!' % self.name.upper())
        else:
            print ('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"



Hello, Fred
HELLO, FRED!


# **Numpy**

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

To use Numpy, we first need to import the numpy package:

In [88]:

import numpy as np


# **Arrays**

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [89]:

a = np.array([1, 2, 3])  # Create a rank 1 array
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print (a)           

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [90]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print (b)

[[1 2 3]
 [4 5 6]]


In [92]:

print (b.shape)                   
print (b[0, 0], b[0, 1], b[1, 0])
     

(2, 3)
1 2 4


In [94]:

a = np.zeros((2,2))  # Create an array of all zeros
print (a)
     

[[0. 0.]
 [0. 0.]]


In [95]:

b = np.ones((1,2))   # Create an array of all ones
print (b)
     

[[1. 1.]]


In [96]:

c = np.full((2,2), 7) # Create a constant array
print (c) 

[[7 7]
 [7 7]]


In [97]:

d = np.eye(2)        # Create a 2x2 identity matrix
print (d)
     

[[1. 0.]
 [0. 1.]]


In [98]:

e = np.random.random((2,2)) # Create an array filled with random values
print (e)

[[0.92663688 0.27636236]
 [0.41300756 0.9262088 ]]


# **Array indexing**

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [99]:

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [103]:

print (a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])

2
77


In [104]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing:**

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [105]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [106]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing:**

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [107]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# **Datatypes**

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:



In [108]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


**Array math**

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [109]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [110]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is **sum:**

In [111]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the documentation.

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [112]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## **Broadcasting**

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [113]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [114]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension


In [115]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


# Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the numpy reference to find out much more about numpy. https://numpy.org/doc/stable/reference/