<a href="https://colab.research.google.com/github/gundaminpde/2023-spring/blob/main/01_2_NumPy_python_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a modification of a tutorial of Dr. Tirthajyoti Sarkar, Fremont, CA, 94536. You can find the original one at https://github.com/tirthajyoti/Machine-Learning-with-Python/blob/master/Pandas%20and%20Numpy/Numpy_operations.ipynb

# **Vectors and matrices**

In [1]:
import numpy as np

my_list = [1,2,3]

arr = np.array(my_list)

print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

mat = np.array(my_mat)

print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]  ### 정수가 아닌 숫자 사용

mat = np.array(my_mat)

print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

b = np.array([(1.5,2,3), (4,5,6)])

print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64
Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...
We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## 'arange' and 'linspace'

In [3]:
print("A series of numbers:",np.arange(5,16)) # A series of numbers from low to high

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [4]:
## 소수간(마디)의 길이 지정

print("Numbers spaced apart by 2:",np.arange(0,11,2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [6]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [5]:
### 역순이다.

print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [8]:
### linspace 사용

print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,21))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


# Zeroes, Ones, empty, and Identity matrix


In [9]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))                # Tuple이 아니다.
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4)))            # Notice Tuples

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]
Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5))) ### 상수곱

Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [11]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [12]:

mat1 = np.eye(4)    ### n x n 행렬이어야 하므로 n만 입력한다.
print("Identity matrix of dimension", mat1.shape)
print(mat1)


Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random number generation

np.random. + rand, randn 그리고 randint

In [13]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.35257858 0.98711411 0.28762008]
 [0.21608998 0.78025141 0.96654034]]


In [14]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

### randn 과 rand가 차이가 있음.

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.74821886  0.89854182 -0.87425438]
 [-0.26550286  0.21046814  2.05643082]
 [-0.98498223  2.46840664  0.41212136]
 [ 0.40627106 -1.23666092  0.53814935]]


In [15]:
### randint를 사용하였다.

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw



Random integer vector: [37 15 66 39 57 55 39  9 24 55]

Random integer matrix
[[97 32 69 27]
 [47 48 70 14]
 [58  4  1 78]
 [82 90  8 90]]

20 samples drawn from a dice throw: [5 3 1 2 1 6 6 1 3 5 5 2 4 3 5 3 3 4 5 2]


# Reshaping, min, max, sort

In [20]:
from numpy.random import randint as ri

a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)


print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)

a looks like
 -------------------- 
 [29 92 59 51 11 81 47 67 77 74 70 92 77  2 97 80 41 14  8 59  4 88 58  3
 27 87 61 96 53  1] 
 --------------------

b looks like
 -------------------- 
 [[[29 92 59 51 11]
  [81 47 67 77 74]
  [70 92 77  2 97]]

 [[80 41 14  8 59]
  [ 4 88 58  3 27]
  [87 61 96 53  1]]] 
 --------------------

c looks like
 -------------------- 
 [[29 92 59 51 11]
 [81 47 67 77 74]
 [70 92 77  2 97]
 [80 41 14  8 59]
 [ 4 88 58  3 27]
 [87 61 96 53  1]] 
 --------------------


In [21]:

A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers ri(1,100,10) \n",'-'*50,"\n",A)
print("\nHere is the sorted vector by np.sort(A, kind='mergesort')) \n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of random integers ri(1,100,10) 
 -------------------------------------------------- 
 [91 63 86 64 50 20 94 46 99 50]

Here is the sorted vector by np.sort(A, kind='mergesort')) 
 -------------------------------------------------- 
 [20 46 50 50 63 64 86 91 94 99]


In [22]:

M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[69 49 97 32 52]
 [88 39 21 14 60]
 [99 74 69 40 51]
 [96 12 82 10 67]
 [81 16 96 69 56]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[32 49 52 69 97]
 [14 21 39 60 88]
 [40 51 69 74 99]
 [10 12 67 82 96]
 [16 56 69 81 96]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[69 12 21 10 51]
 [81 16 69 14 52]
 [88 39 82 32 56]
 [96 49 96 40 60]
 [99 74 97 69 67]]


In [25]:
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)
print("Max of a:", a.max())
print("Min of b:", b.min())
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())


a looks like
 -------------------- 
 [96 44 49 20 22 96 93 37 89 71 58 86  3 12 93 60 45 53 42 18 68 64 23 26
 77  5 31 71 89 94] 
 --------------------

b looks like
 -------------------- 
 [[[96 44 49 20 22]
  [96 93 37 89 71]
  [58 86  3 12 93]]

 [[60 45 53 42 18]
  [68 64 23 26 77]
  [ 5 31 71 89 94]]] 
 --------------------

c looks like
 -------------------- 
 [[96 44 49 20 22]
 [96 93 37 89 71]
 [58 86  3 12 93]
 [60 45 53 42 18]
 [68 64 23 26 77]
 [ 5 31 71 89 94]] 
 --------------------
Max of a: 96
Min of b: 3
Max of a location: 0
Max of b location: 0
Max of c location: 0


# Indexing and slicing

In [28]:
arr = np.arange(0,11)
print("Array:",arr)
print("Type:",type(arr))
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Type: <class 'numpy.ndarray'>
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [29]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
--------------------------------
 [[48 22 55 14 67]
 [40 14 68 32 90]
 [93 25 11 42 41]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 68

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 68

Row or column extract
----------------------
Entire row at index 2: [93 25 11 42 41]
Entire column at index 3: [14 32 42]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[32 90]
 [42 41]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[22 14]
 [14 32]]


In [34]:
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

print("\nDouble bracket indexing\n------------------------")
print("Element in (1,3) and (2,4):", mat[[1,2],[3,4]])


Matrix of random 2-digit numbers
--------------------------------
 [[48 22 55 14 67]
 [40 14 68 32 90]
 [93 25 11 42 41]]

Double bracket indexing
------------------------
Element in (1,3) and (2,4): [32 41]
