<a href="https://colab.research.google.com/github/gundaminpde/2023-spring/blob/main/python_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a modifiction of the CS231n Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).

# **Basic data types**

**Numbers**

In [8]:
x = 3
print (x, type(x))

3 <class 'int'>


In [6]:
print (x + 1)   # Addition;
print (x - 1)   # Subtraction;
print (x * 2)   # Multiplication;
print (x ** 2)  # Exponentiation;

4
2
6
9


In [10]:
x += 1
print (x)  # Prints "4"
x *= 2
print (x)  # Prints "8"

4
8


In [11]:
y = 2.5
print (type(y)) # Prints ""
print (y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


# **Booleans**
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [14]:
t, f = True, False
print (type(t)) # Prints ""
print (type(f))

<class 'bool'>
<class 'bool'>


In [16]:
print (t and f) # Logical AND;
print (t or f)  # Logical OR;
print (not t)   # Logical NOT;
print (t != f)  # Logical XOR;
     

False
True
False
True


# Strings

In [17]:

hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print (hello, len(hello))

hello 5


In [18]:
hw = hello + ' ' + world  # String concatenation
print (hw)  # prints "hello world"

hello world


In [19]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print (hw12)  # prints "hello world 12"

hello world 12


String objects have a bunch of useful methods; for example:

In [20]:

s = "hello"
print (s.capitalize())  # Capitalize a string; prints "Hello"
print (s.upper())       # Convert a string to uppercase; prints "HELLO"
print (s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print (s.center(7) )    # Center a string, padding with spaces; prints " hello "
print (s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print ('  world '.strip())  # Remove leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


# **Containers**
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

**Lists**

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [24]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 2] 2
2


In [25]:
xs[2] = 'foo'    # Lists can contain elements of different types
print (xs)

[3, 1, 'foo']


In [26]:
xs.append('bar') # Add a new element to the end of the list
print(xs) 

[3, 1, 'foo', 'bar']


In [27]:
x = xs.pop()     # Remove and return the last element of the list
print (x, xs)

bar [3, 1, 'foo']


# **Slicing**


In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:



In [34]:
##nums = [i for i in range(5)] 
##nums = range(5) ## it does not work.

nums = list(range(5)) # range is a built-in function that can creates a list of integers

print (nums)         # Prints "[0, 1, 2, 3, 4]"
print (nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print (nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print (nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print (nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print (nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4]=[8,9] # Assign a new sublist to a slice
print (nums )        # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


# **Loops**

You can loop over the elements of a list like this:

In [35]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [36]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


# **List comprehensions:**

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [38]:

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)
     

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [40]:

nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


In [42]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)
     

[0, 4, 16]


# **Dictionaries**

A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [57]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print (d['cat'])      # Get an entry from a dictionary; prints "cute"
print ('cat' in d)    # Check if a dictionary has a given key; prints "True"

cute
True


In [58]:

d['fish'] = 'wet'    # Set an entry in a dictionary
print (d['fish'])      # Prints "wet"
     

wet


In [59]:
print (d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: ignored

In [60]:

print (d.get('monkey', '없다')) # Get an element with a default; prints "없다"
print (d.get('fish', '없다'))   # Get an element with a default; prints "wet"

없다
wet


In [61]:
del d['fish']        # Remove an element from a dictionary
print (d)
print (d.get('fish', '없다')) # "fish" is no longer a key; prints "N/A"

{'cat': 'cute', 'dog': 'furry'}
없다


In [62]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the iteritems method:

In [72]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d.items(): 
    print ('A %s has  %d legs ' % animal)

A person has  2 legs 
A cat has  4 legs 
A spider has  8 legs 


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [74]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print (even_num_to_square)

{0: 0, 2: 4, 4: 16}


# **Sets**

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [76]:

animals = {'cat', 'dog'}
print ('cat' in animals)   # Check if an element is in a set; prints "True"
print ('fish' in animals)  # prints "False"

True
False


In [77]:
animals.add('fish')      # Add an element to a set
print ('fish' in animals)
print (len(animals) )      # Number of elements in a set;

True
3


In [78]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print (len(animals) )      
animals.remove('cat')    # Remove an element from a set
print (len(animals) )

3
2


In [79]:

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: dog
#3: cat


In [81]:
from math import sqrt

print ({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


# **Tuples**

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [82]:

d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print (type(t))
print (d[t])       
print (d[(1, 2)])

<class 'tuple'>
5
1


In [83]:

t[0] = 1

TypeError: ignored

# **Functions**

Python functions are defined using the def keyword. For example:

In [84]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print (sign(x))

negative
zero
positive


In [86]:
def hello(name, loud=False):
    if loud:
        print ('HELLO, %s' % name.upper())
    else:
        print ('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


# **Classes**

The syntax for defining classes in Python is straightforward:

In [87]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print ('HELLO, %s!' % self.name.upper())
        else:
            print ('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"



Hello, Fred
HELLO, FRED!


# **Numpy**

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

To use Numpy, we first need to import the numpy package:

In [88]:

import numpy as np


# **Arrays**

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [89]:

a = np.array([1, 2, 3])  # Create a rank 1 array
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print (a)           

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [90]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print (b)

[[1 2 3]
 [4 5 6]]


In [92]:

print (b.shape)                   
print (b[0, 0], b[0, 1], b[1, 0])
     

(2, 3)
1 2 4


In [94]:

a = np.zeros((2,2))  # Create an array of all zeros
print (a)
     

[[0. 0.]
 [0. 0.]]


In [95]:

b = np.ones((1,2))   # Create an array of all ones
print (b)
     

[[1. 1.]]


In [96]:

c = np.full((2,2), 7) # Create a constant array
print (c) 

[[7 7]
 [7 7]]


In [97]:

d = np.eye(2)        # Create a 2x2 identity matrix
print (d)
     

[[1. 0.]
 [0. 1.]]


In [98]:

e = np.random.random((2,2)) # Create an array filled with random values
print (e)

[[0.92663688 0.27636236]
 [0.41300756 0.9262088 ]]


# **Array indexing**

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [99]:

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [103]:

print (a[0, 1])  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])

2
77
